version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.AspNetCore.OData
    versions:
    - 7.5.4
    - 7.5.5
  - dependency-name: Microsoft.AspNetCore.Identity.EntityFrameworkCore
    versions:
    - 5.0.1
    - 5.0.2
  - dependency-name: Microsoft.EntityFrameworkCore.Design
    versions:
    - 5.0.1
    - 5.0.2
  - dependency-name: Microsoft.AspNetCore.SpaServices.Extensions
    versions:
    - 5.0.1
    - 5.0.2
  - dependency-name: Microsoft.EntityFrameworkCore
    versions:
    - 5.0.1
    - 5.0.2
  - dependency-name: Microsoft.EntityFrameworkCore.InMemory
    versions:
    - 5.0.1
    - 5.0.2
  - dependency-name: Microsoft.EntityFrameworkCore.SqlServer
    versions:
    - 5.0.1
    - 5.0.2
  - dependency-name: OpenIddict
    versions:
    - 3.0.0
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
  - dependency-name: OpenIddict.EntityFrameworkCore
    versions:
    - 3.0.0
- package-ecosystem: npm
  directory: "/Playground.Client"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: autorest
    versions:
    - 3.0.6322
    - 3.0.6335
- package-ecosystem: npm
  directory: "/playground.frontend"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@angular/cli"
    versions:
    - 11.0.5
    - 11.1.2
  - dependency-name: "@types/node"
    versions:
    - 14.14.17
    - 14.14.22
  - dependency-name: karma
    versions:
    - 5.2.3
    - 6.0.3
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.2
    - 3.6.3
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.1002.0
  - dependency-name: rxjs
    versions:
    - 6.6.3
